# Generated by Django 3.2.9 on 2021-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_user.png', max_length=500, upload_to='profile_pics'),
        ),
    ]
