# Generated by Django 3.2.9 on 2021-11-25 09:29

import api.validator
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('slug', models.SlugField(default='', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('devotion_vid', models.FileField(upload_to='dev-vids', validators=[api.validator.validate_devotion_size])),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_poster', models.ImageField(upload_to='event_posters')),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('date_liked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_title', models.CharField(default='New Notification', max_length=100)),
                ('notify_alert', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('devotion_slug', models.CharField(max_length=100)),
                ('prayerlist_slug', models.CharField(blank=True, max_length=100)),
                ('story_slug', models.CharField(blank=True, max_length=100)),
                ('event_slug', models.CharField(blank=True, max_length=100)),
                ('announcement_slug', models.CharField(blank=True, max_length=100)),
                ('likes_slug', models.CharField(blank=True, max_length=100)),
                ('comments_slug', models.CharField(blank=True, max_length=100)),
                ('prayfor_slug', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('date_notified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_title', models.CharField(max_length=200)),
                ('prayer_request', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_text', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.FileField(upload_to='stories', validators=[api.validator.validate_story_size])),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
