# Generated by Django 3.2.9 on 2021-11-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stories',
            name='views',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayfor',
            name='prayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prayerlist'),
        ),
        migrations.AddField(
            model_name='prayfor',
            name='user',
            field=models.ManyToManyField(related_name='prayee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyme',
            name='notify_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifyme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='devotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.devotion'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='devotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.devotion'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentee', to=settings.AUTH_USER_MODEL),
        ),
    ]
