# Generated by Django 3.2.9 on 2022-01-02 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stories',
            name='user_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofilepic', to='users.profile'),
        ),
        migrations.AddField(
            model_name='prayfor',
            name='prayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prayerlist'),
        ),
        migrations.AddField(
            model_name='prayfor',
            name='user',
            field=models.ManyToManyField(related_name='prayee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prayerlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
