# Generated by Django 3.2.9 on 2022-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
