# Generated by Django 3.2.9 on 2022-10-11 11:44

import api.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='devotional_video',
            field=models.FileField(null=True, upload_to='devotion_videos', validators=[api.validator.validate_devotion_size]),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.FileField(upload_to='stories', validators=[api.validator.validate_devotion_size]),
        ),
    ]
