# Generated by Django 3.2.9 on 2022-01-10 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stories_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='posted_at',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
