# Generated by Django 3.2.9 on 2022-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221011_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
