# Generated by Django 3.2.9 on 2021-11-25 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_stories_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liking_devotion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
