# Generated by Django 3.2.9 on 2022-01-10 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stories_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='stories',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
