# Generated by Django 3.2.9 on 2022-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dailydevotion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='devotional_video',
            field=models.FileField(null=True, upload_to='devotion_videos'),
        ),
        migrations.AlterField(
            model_name='dailydevotion',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailydevotion',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
