# Generated by Django 3.2.9 on 2022-10-12 08:03

import api.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221012_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydevotion',
            name='devotional_video',
            field=models.FileField(null=True, upload_to='devotion_videos', validators=[api.validator.validate_devotion_size]),
        ),
    ]
