# Generated by Django 3.2.9 on 2021-12-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211206_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageBox',
            new_name='ImageBoxes',
        ),
        migrations.RenameModel(
            old_name='VidBox',
            new_name='VidBoxes',
        ),
    ]
