# Generated by Django 3.2.9 on 2022-10-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dailydevotion_devotional_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydevotion',
            name='likes',
        ),
    ]
