# Generated by Django 3.2.9 on 2021-12-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211206_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotion',
            name='devotion_vid',
        ),
    ]
