# Generated by Django 3.2.9 on 2022-10-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_dailydevotion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_poster',
            field=models.ImageField(blank=True, upload_to='event_posters'),
        ),
    ]
