# Generated by Django 3.2.9 on 2021-12-09 13:28

import api.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_devotion_devotion_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='devotion_vid',
            field=models.FileField(default='', upload_to='dev-vids', validators=[api.validator.validate_devotion_size]),
            preserve_default=False,
        ),
    ]
