# Generated by Django 3.2.9 on 2021-12-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_devotion_devotion_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageboxes',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vidboxes',
            name='vid',
            field=models.CharField(max_length=500),
        ),
    ]
