# Generated by Django 3.2.9 on 2021-12-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_imageboxes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devotion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='message',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='views',
        ),
        migrations.DeleteModel(
            name='NotifyMe',
        ),
    ]
