# Generated by Django 3.2.9 on 2021-12-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211215_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VidBoxes',
        ),
        migrations.AlterField(
            model_name='devotion',
            name='devotion_vid',
            field=models.TextField(),
        ),
    ]
