# Generated by Django 3.2.9 on 2021-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211215_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotion',
            old_name='devotion_vid',
            new_name='message',
        ),
        migrations.AddField(
            model_name='devotion',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devotion',
            name='title',
            field=models.CharField(default='Morning Devotion', max_length=200),
            preserve_default=False,
        ),
    ]
