# Generated by Django 3.2.9 on 2021-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211216_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotion',
            name='devotion_vid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
