# Generated by Django 3.2.9 on 2021-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_devotion_devotion_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_url', models.CharField(default='', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='devotion',
            name='devotion_vid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
