# Generated by Django 3.2.9 on 2021-12-28 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='date_posted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
